/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edu.sise.gui;

import com.edu.sise.entidades.Provincia;
import com.edu.sise.entidades.Tutor;
import com.edu.sise.logic.DepartamentoLogic;
import com.edu.sise.logic.ProvinciaLogic;
import com.edu.sise.logic.TutorLogic;
import java.time.LocalDate;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author CLIENTE
 */
public class ifrmTutores extends javax.swing.JInternalFrame {

   private TutorLogic logica;
   private DepartamentoLogic logicaDepa;
    private ProvinciaLogic logicaProvincia;
     /* Creates new form ifrmTutoress
     */
    public ifrmTutores() {
        initComponents();
        logica = new TutorLogic();
        logicaProvincia = new ProvinciaLogic();
        logicaDepa = new DepartamentoLogic();
        
        //llenar el combo Provincia al iniciar el ifrm
        logicaProvincia.llenarComboProvincia(cboDepartamentos);
        //logicaDepa.llenarDepartamento(cboDepartamentos);
        logica.imprimir(tbLista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnListar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnGuard = new javax.swing.JButton();
        btnElim = new javax.swing.JButton();
        btnModi = new javax.swing.JButton();
        txtCarMa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLista = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cboDepartamentos = new javax.swing.JComboBox<>();
        txtDni = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPapell = new javax.swing.JTextField();
        txtSapell = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        dtpFnac = new org.jdatepicker.JDatePicker();
        jLabel8 = new javax.swing.JLabel();
        txtTele = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txtBusq = new javax.swing.JTextField();
        btnBusq = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Opciones"));

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edu/sise/gui/resources/salirr.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnGuard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edu/sise/gui/resources/guardar.png"))); // NOI18N
        btnGuard.setText("Guardar");
        btnGuard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardActionPerformed(evt);
            }
        });

        btnElim.setText("Eliminar");
        btnElim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElimActionPerformed(evt);
            }
        });

        btnModi.setText("Modificar");
        btnModi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModiActionPerformed(evt);
            }
        });

        txtCarMa.setText("Carga Masiva");
        txtCarMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarMaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCarMa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnModi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnElim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGuard)
                .addGap(18, 18, 18)
                .addComponent(btnSalir)
                .addGap(18, 18, 18)
                .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnElim, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnModi, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(txtCarMa, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        tbLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbListaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbLista);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos Tutores"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("ID");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 140, 30));

        jLabel4.setText("NOMBRE");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        txtId.setEditable(false);
        txtId.setBackground(java.awt.SystemColor.inactiveCaption);
        txtId.setEnabled(false);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jPanel2.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 69, -1));

        jLabel1.setText("PROVINCIAS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        cboDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDepartamentosActionPerformed(evt);
            }
        });
        jPanel2.add(cboDepartamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 180, 30));
        jPanel2.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 80, 30));

        jLabel2.setText("DNI");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel5.setText("P. Apellido");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel6.setText("S. Apellido");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));
        jPanel2.add(txtPapell, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 150, 30));
        jPanel2.add(txtSapell, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 150, 30));

        jLabel7.setText("F.NAC");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));
        jPanel2.add(dtpFnac, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        jLabel8.setText("TELEFONO");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, -1));
        jPanel2.add(txtTele, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 120, 30));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Búsqueda"));
        jPanel3.setToolTipText("Busqueda");

        txtBusq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusqKeyReleased(evt);
            }
        });

        btnBusq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edu/sise/gui/resources/1055031_magnifying_search_view_icon.png"))); // NOI18N
        btnBusq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBusq, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnBusq, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnBusq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBusq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 480, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed

  
        tbLista.setModel(new TutorLogic().getModelo());

    }//GEN-LAST:event_btnListarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGuardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardActionPerformed

        int anio, mes, dia;
        anio = dtpFnac.getModel().getYear();
        mes = dtpFnac.getModel().getMonth()+1;
        dia = dtpFnac.getModel().getDay();
        
        
        
        Tutor o = new Tutor(
Integer.parseInt((txtId.getText().isEmpty())?"-1":txtId.getText()),
        txtDni.getText(),
        txtNombre.getText(),
   txtPapell.getText(),
   txtSapell.getText(),
   LocalDate.of(anio, mes, dia),
   txtTele.getText(),
   ((Provincia)cboDepartamentos.getSelectedItem()).getId_prov());
boolean rpta = logica.agegarTutor(o);
if (rpta){
            JOptionPane.showMessageDialog(this, "Se registro correctamente :)");
        }
        else{
            JOptionPane.showMessageDialog(this, "No se pudo registrar correctamente :( ");
        }
        
 logica.imprimir(tbLista);

    }//GEN-LAST:event_btnGuardActionPerformed

    private void btnElimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElimActionPerformed
    
      int respuesta = JOptionPane.showConfirmDialog(this, "¿Desea realmente eliminar el registro?", "SISTEMAS", JOptionPane.YES_NO_OPTION);
     
        if(respuesta == JOptionPane.YES_OPTION){
            int id_prov = Integer.parseInt(txtId.getText());
            boolean rpta = logica.eliminarTutor(id_prov);
            if(rpta){
                JOptionPane.showMessageDialog(this, "Se elimino correctamente");
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo elimino");
            }
        }
        logica.imprimir(tbLista);
       
    }//GEN-LAST:event_btnElimActionPerformed

    private void btnModiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModiActionPerformed

 int anio, mes, dia;
        anio = dtpFnac.getModel().getYear();
        mes = dtpFnac.getModel().getMonth()+1;
        dia = dtpFnac.getModel().getDay();
        
        
        
        Tutor o = new Tutor(
                Integer.parseInt((txtId.getText().isEmpty())?"-1":txtId.getText()),
        txtDni.getText(),
        txtNombre.getText(),
   txtPapell.getText(),
   txtSapell.getText(),
   LocalDate.of(anio, mes, dia),
   txtTele.getText(),
   ((Provincia)cboDepartamentos.getSelectedItem()).getId_prov());
        boolean rpta = logica.modificarTutor(o);
        if (rpta){
            JOptionPane.showMessageDialog(this, "Se modifico correctamente :)");
        }
        else{
            JOptionPane.showMessageDialog(this, "No se pudo modificar :( ");
        }
        
        
 logica.imprimir(tbLista);
 

    }//GEN-LAST:event_btnModiActionPerformed

    private void tbListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListaMouseClicked
        //variables
        int fila = -1;
        int id_tutor, id_provv ;
        String dni="", nombre="", papell="",sapell="",telef="";
        LocalDate fnacim;
        //entrada
        fila = tbLista.getSelectedRow();
int x=0;
        //procese y salida
        if (fila>=0) {
            id_tutor=Integer.parseInt( tbLista.getValueAt(fila, x++) +"");
            dni=tbLista.getValueAt(fila, x++)+"";
            nombre=tbLista.getValueAt(fila, x++)+"";
            papell=tbLista.getValueAt(fila, x++)+"";
            sapell=tbLista.getValueAt(fila, x++)+"";
            fnacim= LocalDate.parse(tbLista.getValueAt(fila, x++)+"");
            telef =tbLista.getValueAt(fila, x++) +"";
id_provv=Integer.parseInt( tbLista.getValueAt(fila, x++) +"");
        

        txtId.setText(id_tutor+"");
        txtDni.setText(dni);
        txtNombre.setText(nombre);
        txtPapell.setText(papell);
        txtSapell.setText(sapell);
        dtpFnac.getModel().setDate(fnacim.getYear(), fnacim.getMonthValue()-1,
                fnacim.getDayOfMonth());
        dtpFnac.getModel().setSelected(true);
        txtTele.setText(telef);
        logicaDepa.seleccionarItemCbo(cboDepartamentos, id_provv);

       // logicaTutor.seleccionarItemCbo(cboDepartamentos.getSelectedItem()).get;
logica.imprimir(tbLista);
        }
        
        
    }//GEN-LAST:event_tbListaMouseClicked

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed

    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void cboDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDepartamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDepartamentosActionPerformed

    private void txtCarMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarMaActionPerformed
     JFileChooser buscador = new JFileChooser();
     buscador.showOpenDialog(this);
     
     String rutaArch= buscador.getSelectedFile().getAbsolutePath();
     //logica carga el archivo en base de datos
     int resultados=logica.cargaMasiva(rutaArch);
     
     if(resultados==0)
         JOptionPane.showMessageDialog(this, "No se pudo realizar la carga masiva");
     else
         JOptionPane.showMessageDialog(this, "Se registraron " + resultados+ " registros a la lista");
     
     
     logica.imprimir(tbLista);
    }//GEN-LAST:event_txtCarMaActionPerformed

    private void txtBusqKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusqKeyReleased

        logica.imprimir(tbLista, txtBusq.getText());

    }//GEN-LAST:event_txtBusqKeyReleased

    private void btnBusqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusqActionPerformed
        // logica.imprimir(tbLista, txtBusq.getText());

    }//GEN-LAST:event_btnBusqActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusq;
    private javax.swing.JButton btnElim;
    private javax.swing.JButton btnGuard;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnModi;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cboDepartamentos;
    private org.jdatepicker.JDatePicker dtpFnac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbLista;
    private javax.swing.JTextField txtBusq;
    private javax.swing.JButton txtCarMa;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPapell;
    private javax.swing.JTextField txtSapell;
    private javax.swing.JTextField txtTele;
    // End of variables declaration//GEN-END:variables




}
