/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edu.sise.gui;

import com.edu.sise.entidades.Carrera;
import com.edu.sise.entidades.Provincia;
import com.edu.sise.entidades.Profesor;
import com.edu.sise.logic.CarreraLogic;
import com.edu.sise.logic.DepartamentoLogic;
import com.edu.sise.logic.ProvinciaLogic;
import com.edu.sise.logic.ProfesorLogic;
import java.io.ByteArrayOutputStream;
import java.time.LocalDate;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import net.glxn.qrgen.QRCode;
import net.glxn.qrgen.image.ImageType;


/**
 *
 * @author CLIENTE
 */
public class ifrmProfesores extends javax.swing.JInternalFrame {

   private ProfesorLogic logica;
   private DepartamentoLogic logicaDepa;
    private ProvinciaLogic logicaProvincia;
    private CarreraLogic logicaCarrera;
     /* Creates new form ifrmProfesoress
     */
    public ifrmProfesores() {
        initComponents();
        logica = new ProfesorLogic();
        logicaProvincia = new ProvinciaLogic();
        logicaDepa = new DepartamentoLogic();
        logicaCarrera = new CarreraLogic();
        
        //llenar el combo Provincia al iniciar el ifrm
        logicaProvincia.llenarComboProvincia(cboProv);
        logicaCarrera.llenarComboCarrera(cboCarre);
        //logicaDepa.llenarDepartamento(cboDepartamentos);
        logica.imprimir(tbLista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnListar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnGuard = new javax.swing.JButton();
        btnElim = new javax.swing.JButton();
        btnModi = new javax.swing.JButton();
        txtCarMa = new javax.swing.JButton();
        lblQR = new javax.swing.JLabel();
        btnnQR = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLista = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cboCarre = new javax.swing.JComboBox<>();
        txtDni = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPapell = new javax.swing.JTextField();
        txtSapell = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        dtpFnac = new org.jdatepicker.JDatePicker();
        jLabel8 = new javax.swing.JLabel();
        txtTele = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txtBusq = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cboProv = new javax.swing.JComboBox<>();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Opciones"));

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edu/sise/gui/resources/salirr.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnGuard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edu/sise/gui/resources/guardar.png"))); // NOI18N
        btnGuard.setText("Guardar");
        btnGuard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardActionPerformed(evt);
            }
        });

        btnElim.setText("Eliminar");
        btnElim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElimActionPerformed(evt);
            }
        });

        btnModi.setText("Modificar");
        btnModi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModiActionPerformed(evt);
            }
        });

        txtCarMa.setText("Carga Masiva");
        txtCarMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarMaActionPerformed(evt);
            }
        });

        btnnQR.setText("Generar QR");
        btnnQR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnQRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(23, Short.MAX_VALUE)
                        .addComponent(lblQR, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCarMa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnModi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGuard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnElim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnnQR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGuard)
                .addGap(18, 18, 18)
                .addComponent(btnSalir)
                .addGap(18, 18, 18)
                .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnElim, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnModi, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(txtCarMa, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnnQR, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(lblQR, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        tbLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbListaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbLista);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos Tutores"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("ID");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 140, 30));

        jLabel4.setText("NOMBRE");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        txtId.setEditable(false);
        txtId.setBackground(java.awt.SystemColor.inactiveCaption);
        txtId.setEnabled(false);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jPanel2.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 69, -1));

        jLabel1.setText("PROVINCIAS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        cboCarre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCarreActionPerformed(evt);
            }
        });
        jPanel2.add(cboCarre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 280, 30));
        jPanel2.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 80, 30));

        jLabel2.setText("DNI");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, -1, -1));

        jLabel5.setText("P. Apellido");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel6.setText("S. Apellido");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, -1));
        jPanel2.add(txtPapell, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 150, 30));
        jPanel2.add(txtSapell, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 150, 30));

        jLabel7.setText("F.NAC");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));
        jPanel2.add(dtpFnac, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jLabel8.setText("TELEFONO");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, -1));
        jPanel2.add(txtTele, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 120, 30));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Búsqueda"));
        jPanel3.setToolTipText("Busqueda");

        txtBusq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusqKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(txtBusq, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBusq, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 480, 70));

        jLabel9.setText("CARRERAS");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        cboProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboProvActionPerformed(evt);
            }
        });
        jPanel2.add(cboProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 280, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed

  
        tbLista.setModel(new ProfesorLogic().getModelo());

    }//GEN-LAST:event_btnListarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGuardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardActionPerformed

        int anio, mes, dia;
        anio = dtpFnac.getModel().getYear();
        mes = dtpFnac.getModel().getMonth()+1;
        dia = dtpFnac.getModel().getDay();

        Profesor o = new Profesor(
Integer.parseInt((txtId.getText().isEmpty())?"-1":txtId.getText()),
        txtDni.getText(),
        txtNombre.getText(),
   txtPapell.getText(),
   txtSapell.getText(),
   LocalDate.of(anio, mes, dia),
   txtTele.getText(),
   ((Carrera)cboCarre.getSelectedItem()).getId_carrera(),
   ((Provincia)cboProv.getSelectedItem()).getId_prov());
        
boolean rpta = logica.agegarProfesor(o);
if (rpta){
            JOptionPane.showMessageDialog(this, "Se registro correctamente :)");
        }
        else{
            JOptionPane.showMessageDialog(this, "No se pudo registrar correctamente :( ");
        }
        
 logica.imprimir(tbLista);

    }//GEN-LAST:event_btnGuardActionPerformed

    private void btnElimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElimActionPerformed
    
      int respuesta = JOptionPane.showConfirmDialog(this, "¿Desea realmente eliminar el registro?", "SISTEMAS", JOptionPane.YES_NO_OPTION);
     
        if(respuesta == JOptionPane.YES_OPTION){
            int id_prov = Integer.parseInt(txtId.getText());
            boolean rpta = logica.eliminarProfesor(id_prov);
            if(rpta){
                JOptionPane.showMessageDialog(this, "Se elimino correctamente");
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo elimino");
            }
        }
        logica.imprimir(tbLista);
       
    }//GEN-LAST:event_btnElimActionPerformed

    private void btnModiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModiActionPerformed

 int anio, mes, dia;
        anio = dtpFnac.getModel().getYear();
        mes = dtpFnac.getModel().getMonth()+1;
        dia = dtpFnac.getModel().getDay();
        
        
        
        Profesor o = new Profesor(
                Integer.parseInt((txtId.getText().isEmpty())?"-1":txtId.getText()),
        txtDni.getText(),
        txtNombre.getText(),
   txtPapell.getText(),
   txtSapell.getText(),
   LocalDate.of(anio, mes, dia),
   txtTele.getText(),
   ((Carrera)cboCarre.getSelectedItem()).getId_carrera(),
   ((Provincia)cboProv.getSelectedItem()).getId_prov());
        boolean rpta = logica.modificarProfesor(o);
        if (rpta){
            JOptionPane.showMessageDialog(this, "Se modifico correctamente :)");
        }
        else{
            JOptionPane.showMessageDialog(this, "No se pudo modificar :( ");
        }
        
        
 logica.imprimir(tbLista);
 

    }//GEN-LAST:event_btnModiActionPerformed

    private void tbListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListaMouseClicked
        //variables
        int fila = -1;
        int id_tutor=0, id_provv=0, id_carr =0 ;
        String dni="", nombre="", papell="",sapell="",telef="";
        LocalDate fnacim;
        //entrada
        fila = tbLista.getSelectedRow();
int x=0;
        //procese y salida
        if (fila>=0) {
            id_tutor=Integer.parseInt( tbLista.getValueAt(fila, x++) +"");
            dni=tbLista.getValueAt(fila, x++)+"";
            nombre=tbLista.getValueAt(fila, x++)+"";
            papell=tbLista.getValueAt(fila, x++)+"";
            sapell=tbLista.getValueAt(fila, x++)+"";
            fnacim= LocalDate.parse(tbLista.getValueAt(fila, x++)+"");
            telef =tbLista.getValueAt(fila, x++) +"";
id_carr=Integer.parseInt( tbLista.getValueAt(fila, x++) +"");
id_provv=Integer.parseInt( tbLista.getValueAt(fila, x++) +"");
        

        txtId.setText(id_tutor+"");
        txtDni.setText(dni);
        txtNombre.setText(nombre);
        txtPapell.setText(papell);
        txtSapell.setText(sapell);
        dtpFnac.getModel().setDate(fnacim.getYear(), fnacim.getMonthValue()-1,
                fnacim.getDayOfMonth());
        dtpFnac.getModel().setSelected(true);
        txtTele.setText(telef);
        logicaCarrera.seleccionarItemCbo(cboCarre, id_carr);
        logicaProvincia.seleccionarItemCbo(cboProv, id_provv);

       // logicaProfesor.seleccionarItemCbo(cboDepartamentos.getSelectedItem()).get;
logica.imprimir(tbLista);
        }
        
        
    }//GEN-LAST:event_tbListaMouseClicked

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed

    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void cboCarreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCarreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCarreActionPerformed

    private void txtCarMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarMaActionPerformed
     JFileChooser buscador = new JFileChooser();
     buscador.showOpenDialog(this);
     
     String rutaArch= buscador.getSelectedFile().getAbsolutePath();
     //logica carga el archivo en base de datos
     int resultados=logica.cargaMasiva(rutaArch);
     
     if(resultados==0)
         JOptionPane.showMessageDialog(this, "No se pudo realizar la carga masiva");
     else
         JOptionPane.showMessageDialog(this, "Se registraron " + resultados+ " registros a la lista");
     
     
     logica.imprimir(tbLista);
    }//GEN-LAST:event_txtCarMaActionPerformed

    private void txtBusqKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusqKeyReleased

        logica.imprimir(tbLista, txtBusq.getText());

    }//GEN-LAST:event_txtBusqKeyReleased

    private void cboProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboProvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboProvActionPerformed

    private void btnnQRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnQRActionPerformed


String valor ="";
valor = txtId.getText() +"|"+txtNombre.getText() +"|"+txtPapell.getText()+"|"+txtSapell.getText();

ByteArrayOutputStream qr = QRCode.from(valor).to(ImageType.PNG).stream();

ImageIcon icono = new ImageIcon(qr.toByteArray());
lblQR.setIcon(icono);
//comenzamoss
    }//GEN-LAST:event_btnnQRActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnElim;
    private javax.swing.JButton btnGuard;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnModi;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnnQR;
    private javax.swing.JComboBox<String> cboCarre;
    private javax.swing.JComboBox<String> cboProv;
    private org.jdatepicker.JDatePicker dtpFnac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblQR;
    private javax.swing.JTable tbLista;
    private javax.swing.JTextField txtBusq;
    private javax.swing.JButton txtCarMa;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPapell;
    private javax.swing.JTextField txtSapell;
    private javax.swing.JTextField txtTele;
    // End of variables declaration//GEN-END:variables




}
